### ISSUE TITLE
Branded wallpapers

### ISSUE THREAD

**Issue by apolitech** [UbuntuBudgie/budgie-wallpapers#1]
It'd be nice to have some branding on the wallpapers, like logo or just the name and the version number of the OS

**Comment by RohanVilloth** [comment]
When @Udara-U3 proposed this idea one month ago, I objected it. Coz, at that time we were planning to change the login screen to _Unity Greeter_ which uses the user wallpaper as background and **already has branding** on it. This'd make the logo and wordmark on wallpaper kinda **redundant**. Besides, wallpaper isn't the only use of that image - it's the header image on website, background on GRUB bootloader screen, Syslinux theme, etc. So, having brand elements embedded in it would make reuse difficult. :confused: This is the reason why most other well designed distros and flavors provide the default wallpaper without any branding, wordmark or logo.

However, all these points apply only to the default/main wallpaper. Other community contributed wallpapers shipped with budgie-remix may have subtle hints or abstract representations of the logo or wordmark. :relaxed:
