### ISSUE TITLE
Original images?

### ISSUE THREAD

**Issue by robcresswell** [UbuntuBudgie/budgie-wallpapers#7]
Hi! I can see there is some attempt to losslessly optimise the images, but I imagine these steps impact quality:

```
Scale down image to match 4K (3840x2400) size:
mogrify -resize 3840x <image.jpg>

If image is still huge in size (above 4MB), check it's quality level:
identify -verbose <image.jpg> | grep 'Image:\|Quality'
If higher than 92, reduce it down:
mogrify -quality 92 <image.jpg>
```

I was curious if there are copies of the original images anywhere public? Uncompressed PNGs or similar, rather than compressed 4K jpegs. Thanks!

**Comment by fossfreedom** [comment]
The default compression values have been deliberately chosen not to impact the visible quality on wallpapers shown on normal resolution and 4k resolution. 

In the debian/copyright each file has it's original location , author etc.

Also, if you look at the commits,  usually the original file is added, and a subsequent commit compressed. So you can get the original file as checked in.

**Comment by robcresswell** [comment]
That was insightful, thanks! Sorry for not doing my due diligence. I am still struggling to find the origin of the default (?) wallpaper: https://github.com/UbuntuBudgie/budgie-wallpapers/blob/df3620916dc7bdd2eabcea8959c761b226963e47/ubuntu_budgie_wallpaper1.jpg

The reasoning overall is that there is some colour banding in the purple / blue transition, or at least, appears to be, and I was wondering if this existed in any original version of this.

**Comment by fossfreedom** [comment]
Hi - yes  that link is the original image.

**Comment by robcresswell** [comment]
Gotcha, thanks
